# -*- coding: utf-8 -*-
"""synonymCreration.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hLZVBhv5GiZAjTk7k3ATK3ULZIEykJgv
"""

import requests
import re
from bs4 import BeautifulSoup
with open("/content/file1.txt", 'r') as f:
  a = [line.rstrip('\n') for line in f]
total=[]
tw=[]
syn = []
i = 0
wdd = a.copy()
print(len(a))
for idx,wrd in enumerate(a):
  r = requests.get('http://www.english-bangla.com/bntobn/index/'+wrd)
  c = r.content
  soup = BeautifulSoup(c)
  try:
    main_content = soup.find('span', attrs = {'class': 'format1'}).text
  except:
    words = ["Null"]
    total.append(words)
    continue
  pattern = re.compile('/.+?/(.+?)।').findall(main_content)
  words = []
  for pat in pattern:
    pat = re.split("[,;]",pat)
    for p in pat:
      p = re.sub("[^\u0981-\u09DF] ","",p)
      p = re.sub("^ ","",p)
      words.append(p)
  if words == []:
    words = ["Null"]
  total.append(words)
  for w in words:
    if w in wdd:
      ids = wdd.index(w)
      tw.append([w,wrd])
      if ids<(idx-i):
        print(ids,idx-i)
        print(wrd)
        print(len(total))
        del(total[ids])
        i=i+1
      if ids>(idx-i):
        del(a[a.index(w)])
      del(wdd[ids])
print(len(wdd))

a = ["a","h","s","d","v"]
b = "h"
if b in a:
  ids = a.index(b)
  del(a[ids])
  print(a)
with open("/content/file.txt", 'r') as f:
  a = [line.rstrip('\n') for line in f]
print(a)

with open("/content/file2.txt", 'w') as f:
  for s in tw:
      f.write(str(s) + '\n')

with open("/content/fileW.txt", 'w') as f:
  for s in wdd:
      f.write(str(s) + '\n')

import numpy as np
print(len(total),len(wdd))
print(np.append(np.array(total),np.array(wdd), axis=1).tolist())